// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMBIf-RYochcTs53bBixz812sinHb3FGk',
    appId: '1:426093933424:web:e9cf49b5916dd6d7fc95b5',
    messagingSenderId: '426093933424',
    projectId: 'fluttermad-40332',
    authDomain: 'fluttermad-40332.firebaseapp.com',
    storageBucket: 'fluttermad-40332.appspot.com',
    measurementId: 'G-YXDMECL8NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBV9ZFBcr78ASw-b6wsPEU6iJEY2Rrx7w',
    appId: '1:426093933424:android:9d87a39bf3dd62ccfc95b5',
    messagingSenderId: '426093933424',
    projectId: 'fluttermad-40332',
    storageBucket: 'fluttermad-40332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bF_RmwqpLtxuGDfkGfu7k0_eq-RJnhA',
    appId: '1:426093933424:ios:3edf36f04cfd14b3fc95b5',
    messagingSenderId: '426093933424',
    projectId: 'fluttermad-40332',
    storageBucket: 'fluttermad-40332.appspot.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bF_RmwqpLtxuGDfkGfu7k0_eq-RJnhA',
    appId: '1:426093933424:ios:3edf36f04cfd14b3fc95b5',
    messagingSenderId: '426093933424',
    projectId: 'fluttermad-40332',
    storageBucket: 'fluttermad-40332.appspot.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMBIf-RYochcTs53bBixz812sinHb3FGk',
    appId: '1:426093933424:web:2af782e7436cf470fc95b5',
    messagingSenderId: '426093933424',
    projectId: 'fluttermad-40332',
    authDomain: 'fluttermad-40332.firebaseapp.com',
    storageBucket: 'fluttermad-40332.appspot.com',
    measurementId: 'G-WLELG3E9YJ',
  );
}
